### ISSUE TITLE
Adding support for return 2 csu

### ISSUE THREAD

**Issue by cothan** [Boyan-MILANOV/ropium#26]
Support for return2csu 

I think this is fairly simple, we need ROPgadget to search for ROP chain in sym.__libc_csu_init and sym.__libc_csu_fini section, so that the ROP chain will be taken into account.

**Comment by Boyan-MILANOV** [comment]
Hey, 

I didn't really understand the nature of the issue. 

ROPium is a gadget analyzer and chainer but it doesn't collect gadgets by itself. To do so it uses the gadget finder ROPgadget. If you noticed that ROPgadget doesn't collect gadgets from certain sections containing executable code, then it is a ROPgadget issue, not a ROPium one, isn't it ?

**Comment by cothan** [comment]
Yes, it's ROPgadget issue, I think it could be marked as enhancement for ropium.
