### ISSUE TITLE
Concatenation of two ropchains

### ISSUE THREAD

**Issue by nurmukhametov** [Boyan-MILANOV/ropium#27]
How can I concatenate two ropchains?

For example
```python
chain1 = rop.compile('[0xdeadbeef] = 0x67676767')
chain2 = rop.compile('sys_execve(0xdeadbeef, 0, 0)')
```

I could only find out the dump method of chains.

**Comment by Boyan-MILANOV** [comment]
Hey, 

You can now use the '+' operator to concatenate ropchains:

    chain3 = chain1 + chain2 

By the way, it is also possible now to directly store strings in memory with : 

    rop.compile('[0xdeadbeef] = "mystring\x00")
