### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by nurmukhametov** [Boyan-MILANOV/ropium#28]
It looks like there is a concurrency problem. When I run several instances of ropium at the same time then results are unstable. 

The reason at least is that ROPgadget output captured at the same file.

https://github.com/Boyan-MILANOV/ropium/blob/2b40421b31be948a8dedb01cc713305022647f23/bindings/py_ropium.cpp#L19

**Comment by Boyan-MILANOV** [comment]
Nice catch :) I fixed it, now the tool uses different files for different instances
