### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lifanxin** [Boyan-MILANOV/ropium#33]
when I type "ropium" in the terminal, an error occur: from ropium import *     No module named "ropium"

**Comment by jie-xiao** [comment]
same problem, any suggestion?

**Comment by jie-xiao** [comment]
install prompt_toolkit with >sudo pip3 install prompt_toolkit<  then run ropium with sudo,it works!

**Comment by lifanxin** [comment]
ok, thanks for you suggestion. It's been so long that I've forgotten the question.
